#include <iostream>
#include <memory>
#include "Vriscv_pkg.h"        // Header generated by Verilator
#include "verilated.h"
#include "verilated_vcd_c.h" // For waveform generation

int main(int argc, char** argv) {
    // 1. Initialize Verilator global context arguments
    Verilated::commandArgs(argc, argv);
    
    // 2. Instantiate the module directly (No context wrapper needed)
    auto top = std::make_unique<Vriscv_pkg>();

    // 3. Setup Waveform Tracing (Optional)
    Verilated::traceEverOn(true);
    auto tfp = std::make_unique<VerilatedVcdC>();
    top->trace(tfp.get(), 99); 
    tfp->open("waveform.vcd");

    // 4. Initialize Signals
    top->clk = 0;
    top->rst = 1;

    // 5. Simulation Loop
    uint64_t ticks = 0;
    // Replace context->gotFinish() with Verilated::gotFinish()
    while (!Verilated::gotFinish() && !top->simulation_end) {
        
        // Assert reset for the first 5 clock cycles
        if (ticks > 10) {
            top->rst = 0;
        }

        // Toggle Clock
        if ((ticks % 5) == 0) {
            top->clk = !top->clk;
        }

        // Evaluate the model logic
        top->eval();

        // Dump current signal states to the waveform file (Pass tick count directly)
        tfp->dump(ticks);

        // Periodically print status to console when clock rises
        if (top->clk && (ticks % 10 == 5)) {
            std::cout << "[Cycle " << (ticks / 10) << "] PC: 0x" 
                      << std::hex << top->debug_pc << std::dec << std::endl;
        }

        ticks++;

        // Safety timeout to prevent infinite loops
        if (ticks > 50000) break;
    }

    // 6. Clean up
    tfp->close();
    top->final();
    std::cout << "Simulation finished successfully." << std::endl;
    return 0;
}