#include <cstdint>
#include <cstdio>
#include <iostream>
#include <memory>
#include <vector>

#include "Vriscv_pkg.h"        // Header generated by Verilator
#include "verilated.h"
#include "verilated_vcd_c.h"   // For waveform generation

// Test configuration
static const uint64_t CLK_HZ = 100000000;   // 100 MHz

static const int UART_PSC = 868;
static const double UART_BAUD_NOMINAL = 115200.0;

static const uint64_t TICKS_PER_CLK = 10;
static const uint64_t PS_PER_CLK    = 1000000000000ULL / CLK_HZ;
static const uint64_t PS_PER_TICK   = PS_PER_CLK / TICKS_PER_CLK;

static double cycles_to_us(uint64_t c) {
    return (double)c * 1e6 / (double)CLK_HZ;
}

static bool check(const char* what, bool ok) {
    std::cout << (ok ? "  [PASS] " : "  [FAIL] ") << what << std::endl;
    return ok;
}

class UartMonitor {
public:
    explicit UartMonitor(int psc) : psc_(psc) {}

    void tick(bool line) {
        cycle_++;

        if (line != line_prev_) {
            if (state_ != IDLE) {
                uint64_t gap = cycle_ - last_edge_;
                if (gap % (uint64_t)psc_ != 0) bad_bit_periods_++;
                gap_gcd_ = gcd(gap_gcd_, gap);
            }
            last_edge_ = cycle_;
            line_prev_ = line;
        }

        switch (state_) {
        case IDLE:
            if (!line) {                    // falling edge => candidate start bit
                state_ = START;
                counter_ = 0;
                frame_start_ = cycle_;
                last_edge_ = cycle_; 
            }
            break;

        case START:
            if (++counter_ >= psc_ / 2) {   // sample the middle of the start bit
                if (line) {
                    false_starts_++; 
                    state_ = IDLE;
                } else {
                    state_ = DATA;
                    counter_ = 0;
                    bit_idx_ = 0;
                    shift_ = 0;
                }
            }
            break;

        case DATA:
            if (++counter_ >= psc_) {
                counter_ = 0;
                if (line) shift_ |= (uint8_t)(1u << bit_idx_);
                if (++bit_idx_ == 8) state_ = STOP;
            }
            break;

        case STOP:
            if (++counter_ >= psc_) {
                counter_ = 0;
                if (!line) framing_errors_++;   // stop bit must be high
                bytes_.push_back(shift_);
                starts_.push_back(frame_start_);
                state_ = IDLE;
            }
            break;
        }
    }

    bool mid_frame() const { return state_ != IDLE; }
    uint64_t measured_psc() const { return gap_gcd_; }

    const std::vector<uint8_t>& bytes() const { return bytes_; }
    const std::vector<uint64_t>& starts() const { return starts_; }
    int framing_errors()  const { return framing_errors_; }
    int false_starts()    const { return false_starts_; }
    int bad_bit_periods() const { return bad_bit_periods_; }

private:
    enum State { IDLE, START, DATA, STOP };

    static uint64_t gcd(uint64_t a, uint64_t b) {
        while (b) { uint64_t t = a % b; a = b; b = t; }
        return a;
    }

    const int psc_;
    State state_ = IDLE;
    int counter_ = 0;
    int bit_idx_ = 0;
    uint8_t shift_ = 0;

    bool line_prev_ = true;   // line idles high
    uint64_t last_edge_ = 0;
    uint64_t frame_start_ = 0;
    uint64_t cycle_ = 0;

    int framing_errors_ = 0;
    int false_starts_ = 0;
    int bad_bit_periods_ = 0;
    uint64_t gap_gcd_ = 0;

    std::vector<uint8_t> bytes_;
    std::vector<uint64_t> starts_;
};

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    auto top = std::make_unique<Vriscv_pkg>();

    // 3. Setup Waveform Tracing (Optional)
    Verilated::traceEverOn(true);
    auto tfp = std::make_unique<VerilatedVcdC>();
    top->trace(tfp.get(), 99);
    tfp->open("waveform.vcd");

    // 4. Initialize Signals
    top->clk = 0;
    top->rst_n = 0;
    top->uart_rx = 1;   // rx idles high

    UartMonitor uart_mon(UART_PSC);
    uint64_t ticks = 0;
    uint64_t cycles = 0;
    bool prev_clk = false;
    bool halted = false;
    uint64_t drain_until = 0;

    while (!Verilated::gotFinish()) {
        if (ticks > 10) {
            top->rst_n = 1;
        }

        if ((ticks % 5) == 0) {
            top->clk = !top->clk;
        }

        top->eval();
        tfp->dump(ticks * PS_PER_TICK);

        if (top->clk && !prev_clk && top->rst_n) {
            cycles++;
            uart_mon.tick(top->uart_tx != 0);
        }
        prev_clk = top->clk;

        if (top->simulation_end && !halted) {
            halted = true;
            drain_until = cycles + (uint64_t)UART_PSC * 12;  // ~1 frame
            std::printf("CPU halted at cycle %llu (%.2f us), draining UART...\n", (unsigned long long)cycles, cycles_to_us(cycles));
        }

        if (halted && cycles >= drain_until && !uart_mon.mid_frame()) break;

        ticks++;
        if (ticks > 100000000) {
            std::cout << "TIMEOUT: simulation never halted" << std::endl;
            break;
        }
    }

    // 6. Clean up
    tfp->close();
    top->final();

    // 7. Report
    std::printf("\n=== UART TX ===\n");
    std::printf("  assumed clock: %.3f MHz (%.2f ns period)\n", (double)CLK_HZ / 1e6, 1e9 / (double)CLK_HZ);

    const uint64_t psc = uart_mon.measured_psc();
    if (psc) {
        double baud = (double)CLK_HZ / (double)psc;
        std::printf("  measured bit period: %llu cycles = %.3f us -> %.0f baud (%+.3f%% vs %.0f nominal)\n", (unsigned long long)psc, cycles_to_us(psc), baud, 100.0 * (baud - UART_BAUD_NOMINAL) / UART_BAUD_NOMINAL, UART_BAUD_NOMINAL);
    } else {
        std::printf("  measured bit period: no frames seen\n");
    }

    const auto& rx = uart_mon.bytes();
    for (size_t i = 0; i < rx.size(); i++) {
        char c = (rx[i] >= 0x20 && rx[i] < 0x7f) ? (char)rx[i] : '.';
        std::printf("  byte %2zu: 0x%02X  0b%c%c%c%c%c%c%c%c  '%c'  @cycle %llu (%.2f us)\n",
                    i, rx[i],
                    (rx[i] & 0x80) ? '1':'0', (rx[i] & 0x40) ? '1':'0',
                    (rx[i] & 0x20) ? '1':'0', (rx[i] & 0x10) ? '1':'0',
                    (rx[i] & 0x08) ? '1':'0', (rx[i] & 0x04) ? '1':'0',
                    (rx[i] & 0x02) ? '1':'0', (rx[i] & 0x01) ? '1':'0',
                    c, (unsigned long long)uart_mon.starts()[i],
                    cycles_to_us(uart_mon.starts()[i]));
    }
    std::printf("  %zu byte(s) in %llu cycles (%.2f us)\n",
                rx.size(), (unsigned long long)cycles, cycles_to_us(cycles));

    std::printf("\n=== GPIO ===\n  pins: 0x%02X\n", top->gpio_pins);

    // Hard errors only -- things that are wrong regardless of what the program
    // running on the core happens to send.
    std::cout << "\n=== Errors ===" << std::endl;
    bool ok = true;
    ok &= check("CPU reached halt", halted);
    ok &= check("no UART framing errors (stop bit low)",
                uart_mon.framing_errors() == 0);
    ok &= check("no spurious UART start bits",
                uart_mon.false_starts() == 0);
    ok &= check("all UART bit periods are a multiple of CLOCK_PSC",
                uart_mon.bad_bit_periods() == 0);
    ok &= check("measured bit period == CLOCK_PSC",
                uart_mon.measured_psc() == (uint64_t)UART_PSC);
    ok &= check("no truncated UART frame", !uart_mon.mid_frame());

    std::cout << "\n" << (ok ? "OK" : "ERRORS DETECTED") << std::endl;
    return ok ? 0 : 1;
}
